.PHONY: build install clean

install:
	npm ci
	(cd aw-client-js; npm ci; npm run compile)

update:
	npm run build

clean:
	rm -rf node_modules
	(cd aw-client-js; rm -rf node_modules)

# This is what Google and Mozilla wants us to upload when we release a new version to the Addon "store"
build: install
	npm run build
	zip -r -FS ./smart2po.zip manifest.json android-icon-128x128.png background.js